export const invoices = [
  {
    id: 53,
    customer: "Lamidi Airways",
    project: "Brand Design",
    date: "2023-05-23",
    status: "overdue",
    total: 1698.34,
    paid: 0,
    unpaid: 1698.34,
    items: [
      { description: "Brand identity design", qty: 1, price: 1200 },
      { description: "Logo usage guide", qty: 1, price: 498.34 },
    ],
  },
  {
    id: 54,
    customer: "Just Toyeeb",
    project: "Web Development",
    date: "2023-12-30",
    status: "paid",
    total: 578.38,
    paid: 578.38,
    unpaid: 0,
    items: [
      { description: "Landing page development", qty: 1, price: 420 },
      { description: "Responsive fixes", qty: 1, price: 158.38 },
    ],
  },
  {
    id: 55,
    customer: "Draco Malfoy",
    project: "Logo Design",
    date: "2026-03-09",
    status: "unpaid",
    total: 878,
    paid: 0,
    unpaid: 878,
    items: [
      { description: "Logo concepts", qty: 2, price: 300 },
      { description: "Final logo package", qty: 1, price: 278 },
    ],
  },
  {
    id: 56,
    customer: "Lamin Solt",
    project: "App Design",
    date: "2023-07-24",
    status: "draft",
    total: 1360.43,
    paid: 0,
    unpaid: 1360.43,
    items: [
      { description: "Mobile app UI screens", qty: 8, price: 125 },
      { description: "Prototype setup", qty: 1, price: 360.43 },
    ],
  },
  {
    id: 57,
    customer: "Alade Godxila",
    project: "SEO Audit",
    date: "2023-03-22",
    status: "overdue",
    total: 1280,
    paid: 0,
    unpaid: 1280,
    items: [
      { description: "Technical SEO audit", qty: 1, price: 850 },
      { description: "Keyword report", qty: 1, price: 430 },
    ],
  },
  {
    id: 58,
    customer: "Godfather",
    project: "Consulting",
    date: "2023-05-23",
    status: "paid",
    total: 1370,
    paid: 1370,
    unpaid: 0,
    items: [
      { description: "Strategy consulting", qty: 4, price: 250 },
      { description: "Implementation review", qty: 1, price: 370 },
    ],
  },
];
